#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    Copyright (C) 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>

"""Print chosen file path of a registered icon name for a given size"""

import sys
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

try:
	name = sys.argv[1]
except:
	sys.stderr.write("Missing ICON argument.\n"
	                 "Usage: xdg-icon-paths ICON\n")
	sys.exit(1)

theme = Gtk.IconTheme.get_default()

if not theme.has_icon(name):
	print "icon not found"
	sys.exit(1)

icons = []
# theme.get_icon_sizes() is *very* buggy. Try it with gimp, firefox, etc
for size in xrange(513):
	icon = theme.lookup_icon(name, size, 0).get_filename()
	if icon not in icons:
		icons.append(icon)

for icon in icons:
	print icon
