#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#    Copyright (C) 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>

"""List all regitered icon names matching an optional prefix"""
from __future__ import print_function

import sys
import gi
# ^ See system requirements in readme.md.
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

def usage(ok=True):
	sys.stderr.write("Usage: xdg-icon-list [ICONPREFIX]\n")
	sys.exit(0 if ok else 1)


if len(sys.argv) > 2:
	usage(False)

try:
	name = sys.argv[1]
except:
	name = None

if name in ('-h', '--help'):
	usage()

theme = Gtk.IconTheme.get_default()
for icon in sorted(theme.list_icons(None)):
	if not name or icon.startswith(name):
		print(icon)
