#!/usr/bin/python
import sys
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

try:
	name = sys.argv[1]
except:
	sys.stderr.write("Missing ICON argument.\n"
	                 "Usage: xdg-icon-paths ICON\n")
	sys.exit(1)

theme = Gtk.IconTheme.get_default()

if not theme.has_icon(name):
	print "icon not found"
	sys.exit(1)

icons = []
# theme.get_icon_sizes() is *very* buggy. Try it with gimp, firefox, etc
for size in xrange(513):
	icon = theme.lookup_icon(name, size, 0).get_filename()
	if icon not in icons:
		icons.append(icon)

for icon in icons:
	print icon
