#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    Copyright (C) 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>

"""Run a .desktop file, executing its application"""
# from __future__ import print_function

import sys
from gi.repository import Gio

if __name__ == "__main__":

	try:
		desktop = sys.argv[1]
		uris = sys.argv[2:]
	except:
		sys.stderr.write("Missing DESKTOP-FILE argument.\n"
			"Usage: xdg-desktop-run DESKTOP-FILE [ARGS...]\n")
		sys.exit(1)

	sys.exit(Gio.DesktopAppInfo.new_from_filename(desktop).launch_uris(
		uris, None))
