#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    Copyright (C) 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>

"""
Run a .desktop file, executing its application

Usage:
xdg-desktop-run DESKTOP-FILE [ARGS...]

"""
from __future__ import print_function

import sys
from gi.repository import Gio
# ^ See system requirements in readme.md.

def usage():
	print(__doc__, file=sys.stderr)

def main():
	if len(sys.argv) < 2:
		usage()
		print("Error: Missing DESKTOP-FILE argument.",
			  file=sys.stderr)
		return 1

	desktop = sys.argv[1]
	uris = sys.argv[2:]
	msg = ""
	try:
		info = Gio.DesktopAppInfo.new_from_filename(desktop)
	except TypeError as ex:
		info = None
		if "NULL" in str(ex).upper():
			info = None
			msg = " {}".format(ex)  # "constructor returned NULL"
			# (such as if shortcut has no Desktop Entry section)
		else:
			raise
	if not info:
		print("Error: The shortcut appears to be invalid"
		      " (may be missing [Desktop Entry] section)."+msg)
		return 2
	rc = info.launch_uris(uris, None)
	return rc

if __name__ == "__main__":
	sys.exit(main())
